version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - /data/docker-volumes/jellyfin/config:/config
      - /data/docker-volumes/jellyfin/cache:/cache
      - /data_nas/media/movies:/movies:ro
      - /data_nas/media/tv_shows:/tv_shows:ro
      - /data_nas/media/4k_movies:/4k_movies:ro
      - /data_nas/media/concerts:/concerts:ro
      - /data_nas/media/comedy:/comedy:ro
      - /data_nas/media/music:/music:ro
    ports:
      - 8096:8096
    restart: 'unless-stopped'
