version: "3.1"

services:
    ersatztv:
        image: jasongdove/ersatztv:latest-vaapi
        environment:
            TZ: America/New_York
        ports:
            - "8409:8409"
        volumes:
            - /data/docker-volumes/ersatztv:/root/.local/share/ersatztv
        devices:
            - /dev/dri/renderD128:/dev/dri/renderD128
