version: '3'
services:
  db:
    image: postgres:15.3
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:7.3
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80

volumes:
  db_data:
  pgadmin:
